apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.connector.name }}-ingress
  annotations:
    nginx.org/client-max-body-size: "800m"
spec:
  rules:
  - host: {{ .Values.connector.ingress.hostname }}
    http:
      paths:
      - pathType: Prefix
        path: /api
        backend:
          service:
            name: {{ .Values.connector.name }}
            port:
              number: 19191
      - pathType: Prefix
        path: /control
        backend:
          service:
            name: {{ .Values.connector.name }}
            port:
              number: 19192
      - pathType: Prefix
        path: /management
        backend:
          service:
            name: {{ .Values.connector.name }}
            port:
              number: 19193
      - pathType: Prefix
        path: /protocol
        backend:
          service:
            name: {{ .Values.connector.name }}
            port:
              number: 19194
      - pathType: Prefix
        path: /federatedcatalog
        backend:
          service:
            name: {{ .Values.connector.name }}
            port:
              number: 19195
      - pathType: Prefix
        path: /shared
        backend:
          service:
            name: {{ .Values.connector.name }}
            port:
              number: 19196
      - pathType: Prefix
        path: /public
        backend:
          service:
            name: {{ .Values.connector.name }}
            port:
              number: 19291
      - pathType: Prefix
        path: /inesdata-connector-interface
        backend:
          service:
            name: {{ .Values.connector.name }}-interface
            port:
              number: 8080
{{- if eq .Values.connector.environment "pro" }}
  tls:
  - hosts:
    - {{ .Values.connector.ingress.hostname }}
    secretName: {{ .Values.connector.dataspace }}-{{ .Values.connector.name }}-tls-cert
{{- end }}