keycloak:
  production: true
  auth:
    adminUser: admin
    adminPassword: xxxxCHANGEMExxxx
  postgresql:
    enabled: false
  externalDatabase:
    host: comsrvs-tls-postgres-postgresql
    user: keycloak
    password: xxxxCHANGEMExxxx
    database: keycloak
    port: 5432
  resources:
    requests:
      memory: 2Gi
      cpu: 1000m
    limits:
      memory: 4Gi
      cpu: 2000m
  ingress:
    enabled: true
    hostname: auth.ds.inesdata-project.eu
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.org/ssl-services: "comsrvs-keycloak"
    tls: true
    servicePort: https
    extraTls:
     - secretName: keycloak-pro-tls-cert
       hosts:
       - auth.ds.inesdata-project.eu
  adminIngress:
    enabled: true
    hostname: admin.auth.ds.inesdata.upm
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.org/ssl-services: "comsrvs-keycloak"
    tls: true
    servicePort: https
    extraTls:
      - secretName: keycloak-admin-tls-cert
        hosts:
        - admin.auth.ds.inesdata.upm
  tls:
    enabled: true
    #autoGenerated: true
    existingSecret: keycloak-tls-cert
    usePem: true


