apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Values.dataspace.name }}-registration-service
  name: {{ .Values.dataspace.name }}-registration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: {{ .Values.dataspace.name }}-registration-service
  template:
    metadata:
      labels:
        service: {{ .Values.dataspace.name }}-registration-service
    spec:
      containers:
        - image: {{ .Values.registration.image.name }}:{{ .Values.registration.image.tag }}
          name: registration-service
          ports:
            - containerPort: 8080
              protocol: TCP
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          envFrom:
            - secretRef:
                name: {{ .Values.dataspace.name }}-registration-service-secret
            - configMapRef:
                name: {{ .Values.dataspace.name }}-registration-service-config
      restartPolicy: Always
